cities/urls.py
from django.contrib import admin
from cities.views import *
from django.urls import path

urlpatterns = [
    # path('', home, name='home'),
    path('', CityListView.as_view(), name='home'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    path('add/', CityCreateView.as_view(), name='create'),
]

travel/urls.py
from django.contrib import admin
from routes.views import home, find_routes, add_route, save_route, RouteListView, RouteDetailView, RouteDeleteView
from django.urls import path, include

urlpatterns = [
    path('cities/', include(('cities.urls', 'cities'))),
    path('admin/', admin.site.urls),
    path('trains/', include(('trains.urls', 'trains'))),
    path('accounts/', include(('accounts.urls', 'accounts'))),
    path('', home, name='home'),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('save_route/', save_route, name='save_route'),
    path('list/', RouteListView.as_view(), name='list'),
    path('detail/<int:pk>/', RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', RouteDeleteView.as_view(), name='delete'),

]

routes/models.py
from django.core.exceptions import ValidationError
from django.db import models
from cities.models import City
from trains.models import Train


class Route(models.Model):
    name = models.CharField(max_length=30, unique=True,
                            verbose_name='Название маршрута')
    travel_times = models.PositiveSmallIntegerField(verbose_name='Общее время в пути ')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE,
                                  # null=True , blank=True,
                                  related_name='route_from_city_set',
                                  verbose_name='Из какого города',
                                  )
    to_city = models.ForeignKey('cities.City', on_delete=models.CASCADE,
                                related_name='route_to_city_set',
                                verbose_name='В какой города',
                                )
    trains = models.ManyToManyField(
        'trains.Train', verbose_name='Список поездов')

    def __str__(self):
        return f'Маршрут : {self.name} из города {self.from_city}'

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршрут'
        ordering = ['travel_times']

    def clean(self):
        if self.from_city == self.to_city:
            raise ValidationError('Изменить город отправления')
        qs = Train.objects.filter(
            from_city=self.from_city, to_city=self.to_city,
            travel_time=self.travel_times).exclude(pk=self.pk)
        # Train = self.__class__
        if qs.exists():
            raise ValidationError('Изменить время в пути')

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

templates/about.html
{% extends 'base.html' %}
{% block title %} About {% endblock %}

{% block content %}

 <h1>This is about</h1>

<h3>{{name}}</h3>

{% endblock %}

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'trains:home' as trains_home_url %}
{% url 'trains:create' as trains_create_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'list' as route_list %}
{% url 'detail' as route_detail %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">FindFoute</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item {% if request.path == cities_home_url %} active {% endif %}">
            <a class="nav-link active" aria-current="page" href="{% url 'cities:home' %}">Города</a>
          </li>
          <li class="nav-item {% if request.path == trains_home_url %} active {% endif %}">
            <a class="nav-link" href="{% url 'trains:home' %}">Поезда</a>
          </li>
          <li class="nav-item
          {% if request.path  == route_list or request.path  == route_detail %}
          active
          {% endif %}">
            <a class="nav-link" href="{% url 'list' %}">Маршруты</a>
          </li>
          <li><a class="nav-link" href="{% url 'accounts:login' %}">Войти</a></li>
          <li><a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a></li>
          <li><a class="nav-link" href="{% url 'accounts:register' %}">Регистрация </a></li>
          <li class="nav-item dropdown
          {% if request.path == cities_create_url or request.path == trains_create_url %}active{% endif %}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Добавить
            </a>
            {% if user.is_authenticated %}
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" href="{% url 'cities:create' %}">Новый город</a></li>
          <li><a class="dropdown-item" href="{% url 'trains:create' %}">Новый поезд</a></li>
      </div>
      {% endif %}
      </li>
      </ul>
    </div>
    </div>
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto my-4">
        {% if messages %}
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}

      </div>

    </div>

  </div>
  <div class="container">
    {% block content%}{% endblock %}
  </div>
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->


  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  <script>
    $(document).ready(function() {
      $('.js-example-basic-single').select2();
      $('.js-example-basic-multiple').select2();

    });
  </script>
</body>

</html>

templates/form.html
<div class="row">
  <div class="col-md-4">
    <form action = "{{action}}" method='post'> {% csrf_token %}
            {{form.as_p}}
        <button type="submit" class="btn btn-primary">{{button}}</button>
    </form>
  </div>
</div>